/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: hahahaah (https://sketchfab.com/hahahaah)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nike-air-jordan-888ced6566124a9bac98de87762f9cb8
title: Nike Air Jordan
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model ( { ...props } )
{
  const group = useRef();
  const { nodes, materials } = useGLTF( '/nike_air_jordan.gltf' );
  return (
    <group ref={ group } { ...props } dispose={ null }>
      <group scale={ 1 }>
        <group rotation={ [ -Math.PI / 2, 0, 0 ] }>
          <group rotation={ [ Math.PI / 2, 0, 0 ] }>

            <group position={ [ 0, -0.45, 0 ] }>

              <mesh geometry={ nodes.Object_4.geometry } material={ nodes.Object_4.material } />
              <mesh geometry={ nodes.Object_5.geometry } material={ nodes.Object_5.material } />
            </group>
            <group position={ [ 0, -0.45, 0 ] }>
              <mesh geometry={ nodes.Object_7.geometry } material={ materials[ 'Material.002' ] } />
              <mesh geometry={ nodes.Object_8.geometry } material={ materials[ 'Material.009' ] } />
            </group>
            <group position={ [ 0, -0.45, 0 ] } scale={ 1.03 }>
              <mesh geometry={ nodes.Object_10.geometry } material={ nodes.Object_10.material } />
            </group>
            <group position={ [ 0.72, -0.89, 0 ] }>
              <mesh geometry={ nodes.Object_12.geometry } material={ nodes.Object_12.material } />
            </group>
            <group position={ [ 0, -0.45, 0 ] } scale={ 1.03 }>
              <mesh geometry={ nodes.Object_14.geometry } material={ nodes.Object_14.material } />
            </group>
            <group position={ [ 0, -0.45, 0 ] }>
              <mesh geometry={ nodes.Object_16.geometry } material={ nodes.Object_16.material } />
            </group>
            <group position={ [ 0, -0.45, 0 ] }>
              <mesh geometry={ nodes.Object_18.geometry } material={ nodes.Object_18.material } />
            </group>
            <group position={ [ 0, -0.45, 0 ] }>
              <mesh geometry={ nodes.Object_20.geometry } material={ nodes.Object_20.material } />
            </group>
            <group position={ [ 0, -0.45, 0 ] } scale={ 1.01 }>
              <mesh geometry={ nodes.Object_22.geometry } material={ nodes.Object_22.material } />
            </group>
            <group position={ [ 0, -0.45, 0 ] }>
              <mesh geometry={ nodes.Object_24.geometry } material={ materials[ 'Material.004' ] } />
            </group>
            <group position={ [ 0.3, 0.32, 0 ] } rotation={ [ Math.PI / 2, -0.42, Math.PI / 2 ] } scale={ [ 0.25, 0.16, 1 ] }>
              <mesh geometry={ nodes.Object_26.geometry } material={ nodes.Object_26.material } />
            </group>
            <group position={ [ 0.3, 0.32, 0 ] } rotation={ [ 1.84, -0.42, Math.PI / 2 ] } scale={ [ 0.25, 0.16, 1 ] }>
              <mesh geometry={ nodes.Object_28.geometry } material={ nodes.Object_28.material } />
            </group>
            <group position={ [ -0.85, -0.69, 0 ] } rotation={ [ Math.PI / 2, -1.15, Math.PI / 2 ] } scale={ [ 0.25, 0.16, 1 ] }>
              <mesh geometry={ nodes.Object_30.geometry } material={ nodes.Object_30.material } />
            </group>
            <group position={ [ -0.85, -0.69, 0 ] } rotation={ [ 2.13, -1.1, 1.97 ] } scale={ [ 0.25, 0.16, 1 ] }>
              <mesh geometry={ nodes.Object_32.geometry } material={ nodes.Object_32.material } />
            </group>
            <group position={ [ -0.65, -0.58, 0 ] } rotation={ [ Math.PI / 2, -1.15, Math.PI / 2 ] } scale={ [ 0.25, 0.16, 1 ] }>
              <mesh geometry={ nodes.Object_34.geometry } material={ nodes.Object_34.material } />
            </group>
            <group position={ [ -0.65, -0.58, 0 ] } rotation={ [ 2.13, -1.1, 1.97 ] } scale={ [ 0.25, 0.16, 1 ] }>
              <mesh geometry={ nodes.Object_36.geometry } material={ nodes.Object_36.material } />
            </group>
            <group position={ [ -0.43, -0.47, 0 ] } rotation={ [ Math.PI / 2, -1.07, Math.PI / 2 ] } scale={ [ 0.25, 0.16, 1 ] }>
              <mesh geometry={ nodes.Object_38.geometry } material={ nodes.Object_38.material } />
            </group>
            <group position={ [ -0.43, -0.47, 0 ] } rotation={ [ 2.01, -0.97, 1.83 ] } scale={ [ 0.25, 0.16, 1 ] }>
              <mesh geometry={ nodes.Object_40.geometry } material={ nodes.Object_40.material } />
            </group>
            <group position={ [ -0.23, -0.34, 0 ] } rotation={ [ Math.PI / 2, -0.93, Math.PI / 2 ] } scale={ [ 0.25, 0.16, 1 ] }>
              <mesh geometry={ nodes.Object_42.geometry } material={ nodes.Object_42.material } />
            </group>
            <group position={ [ -0.23, -0.34, 0 ] } rotation={ [ 1.94, -0.84, 1.74 ] } scale={ [ 0.25, 0.16, 1 ] }>
              <mesh geometry={ nodes.Object_44.geometry } material={ nodes.Object_44.material } />
            </group>
            <group position={ [ -0.03, -0.18, 0 ] } rotation={ [ Math.PI / 2, -0.99, Math.PI / 2 ] } scale={ [ 0.25, 0.16, 1 ] }>
              <mesh geometry={ nodes.Object_46.geometry } material={ nodes.Object_46.material } />
            </group>
            <group position={ [ -0.03, -0.19, 0 ] } rotation={ [ 1.97, -0.9, 1.78 ] } scale={ [ 0.25, 0.16, 1 ] }>
              <mesh geometry={ nodes.Object_48.geometry } material={ nodes.Object_48.material } />
            </group>
            <group position={ [ 0.11, -0.02, 0 ] } rotation={ [ Math.PI / 2, -0.64, Math.PI / 2 ] } scale={ [ 0.25, 0.16, 1 ] }>
              <mesh geometry={ nodes.Object_50.geometry } material={ nodes.Object_50.material } />
            </group>
            <group position={ [ 0.11, -0.02, 0 ] } rotation={ [ 1.86, -0.57, 1.62 ] } scale={ [ 0.25, 0.16, 1 ] }>
              <mesh geometry={ nodes.Object_52.geometry } material={ nodes.Object_52.material } />
            </group>
            <group position={ [ 0.72, -0.89, 0 ] }>
              <mesh geometry={ nodes.Object_54.geometry } material={ nodes.Object_54.material } />
              <mesh geometry={ nodes.Object_55.geometry } material={ nodes.Object_55.material } />
            </group>
            <group position={ [ 0, -0.45, 0 ] }>
              <mesh geometry={ nodes.Object_57.geometry } material={ materials[ 'Material.010' ] } />
            </group>
            <group position={ [ 0, -0.45, 0 ] }>
              <mesh geometry={ nodes.Object_59.geometry } material={ nodes.Object_59.material } />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload( '/nike_air_jordan.gltf' );
