/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: quaz30 (https://sketchfab.com/quaz30)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nike-air-zoom-pegasus-36-00fd99e778c244c3bd3b65f99dad7cb2
title: Nike Air Zoom Pegasus 36
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model ( { ...props } )
{
  const group = useRef();
  const { nodes, materials } = useGLTF( '/nike2.gltf' );
  return (
    <group ref={ group } { ...props } dispose={ null }>
      <group scale={ 2.5 }>
        <group rotation={ [ -Math.PI / 2, 0, 0 ] }>
          <group rotation={ [ Math.PI / 2, 0, 0 ] }>

            <mesh geometry={ nodes.defaultMaterial.geometry } material={ materials.NikeShoe } />
          </group>
        </group>
      </group>
    </group >
  );
}

useGLTF.preload( '/nike2.gltf' );
