/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: basti123diaz (https://sketchfab.com/basti123diaz)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/nike-air-force-1-dd24e205763f401b8d7d8cd7e00e495d
title: Nike Air Force 1
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model ( { ...props } )
{
  const group = useRef();
  const { nodes, materials } = useGLTF( '/nike.gltf' );
  return (
    <group ref={ group } { ...props } dispose={ null } >
      <group rotation={ [ -Math.PI / 2, 0, 0 ] }>
        <group scale={ 18 }>
          <mesh geometry={ nodes.Object_2.geometry } material={ materials.textured_0 } />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload( '/nike.gltf' );
